# Generated by Django 3.1.2 on 2020-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
